### ISSUE TITLE
'wine: failed to initialize' after 'protontricks -c 'wine64 uninstaller' 359320'

### ISSUE THREAD

**Issue by Temoli** [redmcg/wine-mono#4]
Running:
`protontricks -c 'wine64 uninstaller' 359320`
returns:
`wine: failed to initialize: /home/vagrant/build-experimental_5.13-local/dist/dist/lib64/wine/ntdll.dll.so: cannot open shared object file: No such file or directory`

Linux Mint 19; GTX 1070, 460.32.03; 'Proton Experimental' and Proton 5.13-5

**Comment by redmcg** [comment]
Hi @Temoli, it looks like someone on ProtonDB has reported something similar:
https://www.protondb.com/app/359320#EhDlaDR0cB

Their solution was to remove their wine prefix. I'd recommend you try this too.

Note that the 'uninstaller' program is a part of wine and therefore can't be fixed in wine-mono. For that reason I'll close this issue. 

But it's a pretty fundamental part of wine, so I doubt it has a bug. Likely it's related to incompatible state between wine versions and therefore a deletion of your prefix should resolve it. 

Please let me know how you go (so I can refer others to this issue should you have success).

**Comment by Temoli** [comment]
Sorry for this not so short delay, my life went bananas because of this covid crap

Shortly after this report I have noticed that the game actually launches but always after around 10 minutes. Later, I did not play it

Yesterday I tried to lunch it after a few updates to the game itself. I have noticed that also Proton changed to version 6.x and now games launches normally

**Comment by redmcg** [comment]
No worries. Thanks for reporting back.
